knowledge_prompt_path: prompts/knowledge_prompt.txt
order_prompt_path: prompts/order_prompt.txt
report_prompt_path: prompts/report_prompt.txt
weather_prompt_path: prompts/weather_prompt.txt
rag_summarize_prompt_path: prompts/rag_summarize.txt
