from pathlib import Path
p = Path(r'c:\Users\一叶知秋\Desktop\新社区项目\Community_Agent\agent\graph\executor.py')
lines = [
'"""LangGraph 多 Agent 主执行器 — 工程化显式 worker 节点版本。"""',
'',
'from __future__ import annotations',
'',
'import threading',
'',
'from langchain_core.messages import HumanMessage, SystemMessage',
'from langgraph.graph import END, StateGraph',
'',
'from agent.graph.agents import (',
'    create_knowledge_agent,',
'    create_order_agent,',
'    create_report_agent,',
'    create_weather_agent,',
')',
'from agent.graph.state import AgentState',
'from agent.graph.supervisor import supervisor_route',
'from agent.graph.worker import run_worker',
'from agent.reflection_service import ReflectionService',
'from memory.user_long_memory_service import UserLongMemoryService',
'from models.dto import ChatHistoryMessage',
'from models.factory import chat_model',
'from utils.logger_handler import logger',
'',
'ROUTE_TO_NODE = {',
'    "knowledge": "knowledge_worker",',
'    "order": "order_worker",',
'    "report": "report_worker",',
'    "weather": "weather_worker",',
'}',
'',
'',
'class MultiAgentExecutor:',
'    def __init__(self):',
'        self.knowledge_agent = create_knowledge_agent()',
'        self.order_agent = create_order_agent()',
'        self.report_agent = create_report_agent()',
'        self.weather_agent = create_weather_agent()',
'        self.reflection_service = ReflectionService(chat_model)',
'        self.user_memory_service = UserLongMemoryService()',
'        self.graph = self._build_graph().compile()',
'',
'    def execute_stream(self, query: str, token: str | None = None, session_id: str | None = None, chat_history: list[ChatHistoryMessage] | None = None, user_id: int | None = None, community_id: int | None = None):',
'        logger.info(f"[MultiAgent] query={query[:200]}")',
'        user_memory_context = self.user_memory_service.build_memory_context(user_id, community_id)',
'        base_messages = self._build_base_messages(query, chat_history, user_memory_context)',
'        state: AgentState = {"query": query, "original_query": query, "token": token, "session_id": session_id, "chat_history": chat_history, "user_id": user_id, "community_id": community_id, "user_memory_context": user_memory_context, "routes": [], "current_route_index": 0, "current_route": "", "current_worker": "", "messages": base_messages, "route_messages": base_messages, "route_answers": [], "called_tools": [], "tool_observations": [], "chart_outputs": [], "control_outputs": [], "food_order_card": None, "final_answer": "", "reflection_attempt": 0, "should_retry": False, "done": False}',
'        emitted_chart_urls: set[str] = set()',
'        emitted_control_keys: set[str] = set()',
'        confirmed_answer = ""',
'        for chunk in self.graph.stream(state, stream_mode="updates"):',
'            for node_name, node_state in chunk.items():',
'                for chart in (node_state.get("chart_outputs") or []):',
'                    url = (chart.get("content") or {}).get("imageUrl", "")',
'                    if url and url not in emitted_chart_urls:',
'                        emitted_chart_urls.add(url)',
'                        yield chart',
'                for ctrl in (node_state.get("control_outputs") or []):',
'                    key = str(ctrl)',
'                    if key not in emitted_control_keys:',
'                        emitted_control_keys.add(key)',
'                        yield ctrl',
'                if node_name == "reflector":',
'                    if node_state.get("should_retry", False):',
'                        yield {"type": "status", "stage": "reflecting", "message": "发现结果需要修正，正在根据反思意见重新执行"}',
'                    else:',
'                        confirmed_answer = node_state.get("final_answer") or confirmed_answer',
'                if node_name == "memory_updater":',
'                    final_answer = node_state.get("final_answer") or confirmed_answer',
'                    self._async_update_memory(user_id, community_id, query, final_answer)',
'                    if final_answer:',
'                        yield final_answer',
]
p.write_text("\n".join(lines) + "\n", encoding='utf-8')
